### ISSUE TITLE
Preenchimento do conteudo da lista de filmes preferidos

### ISSUE THREAD

**Issue by xLooKsx** [xLooKsx/Aula9#1]
Cada membro do grupo devera preencher a pagina docs/filmes.md com seus 4 filmes preferidos.

NÂO EDITEM A PAGINA NO BRANCH**MASTER**.CRIE UM NOVO BRANCH,  EDITE O ARQUIVO E CRIE UM PULL REQUEST QUANDO FINALIZAR

**Comment by xLooKsx** [comment]
:)

**Comment by moisescs** [comment]
:)
